


export const POST_SIGNUP_REQUEST = "POST_SIGNUP_REQUEST";
export const POST_SIGNUP_SUCCESS = "POST_SIGNUP_SUCCESS";
export const POST_SIGNUP_ERROR   = "POST_SIGNUP_ERROR";



export const GET_LOGIN_REQUEST = "GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_ERROR   = "GET_LOGIN_ERROR";


